ALTER TABLE reserva ADD COLUMN IF NOT EXISTS descripcion VARCHAR(1000) NULL;
ALTER TABLE reserva ADD COLUMN IF NOT EXISTS progreso INT NOT NULL DEFAULT 0;
ALTER TABLE reserva ADD COLUMN IF NOT EXISTS notas_progreso VARCHAR(500) NULL;
