ALTER TABLE mensaje
    ADD COLUMN IF NOT EXISTS editado      TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fecha_edicion DATETIME   NULL,
    ADD COLUMN IF NOT EXISTS eliminado    TINYINT(1) NOT NULL DEFAULT 0;
